### ISSUE TITLE
game not launching after chaning wine version

### ISSUE THREAD

**Issue by dan-dan-dslkfnsdoifjsdoim** [an-anime-team/sleepy-launcher#19]
[debug.log](https://github.com/user-attachments/files/16444518/debug.log)
![Screenshot from 2024-08-01 00-07-40](https://github.com/user-attachments/assets/fdaf1987-d371-4111-81d7-13a8282f0403)
Here i tried launching the game on wine staging tkg 9.12 since it says that 9.13 is not recommended. 

Moreover attempting to repair game throws:
[Screencast from 2024-08-01 00-10-03.webm](https://github.com/user-attachments/assets/55d0ffcc-4d16-4a67-8cb7-b98eb91fbaf7)

the debug is attached and this happened on Ubuntu 24.04.

**Comment by krypt0nn** [comment]
This is expected degradation. I had to remove the 9.13 version because it doesn't contain needed video decoding components for this game. You have to manually switch to older versions.

**Comment by dan-dan-dslkfnsdoifjsdoim** [comment]
i just recently changed the version to 9.12, this is what happened after changing

**Comment by dan-dan-dslkfnsdoifjsdoim** [comment]
the same thing is also happening to other game they can't find wine

**Comment by bcrescimanno** [comment]
An update was pushed for the launchers on July 31 that removed Wine-Staging-TkG 9.13 due to a regression in H.264 in that version.  If your launcher is giving you an error that it "Cannot find wine executable," ensure that you have Wine-Staging-TkG 9.12 downloaded. Then:

1. Ensure that you have version 9.11 and 9.12 downloaded.
2. Use the UI to select version 9.11. 
3. After the prefix is updated, use the UI to select version 9.12
4. The prefix will update again.

Then you can remove 9.11. These steps will force the launcher to update the configuration and update the wine prefix.

**Comment by dan-dan-dslkfnsdoifjsdoim** [comment]
now its working, thank you
